cas-initializr:
  metadata-api-key: ${CAS_PROJECT_DB_API_KEY:}
  metadata-url: ${CAS_PROJECT_DB_URL_ENDPOINT:}
server:
  port: ${PORT:8080}
  ssl:
    enabled: false
debug: false

management:
  security:
    enabled: false
  server:
    port: ${MGMT_PORT:${PORT:8080}}
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'info,health,shutdown,supportedVersions'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    shutdown:
      enabled: ${SHUTDOWN_ENABLED:true}
    supportedVersions:
      enabled: true

logging:
  level:
    org:
      ehcache: warn
      springframework:
        web: warn
      apereo:
        cas: info
    io:
      spring:
        initializr: info
spring:
  profiles:
    include: initializr
  cloud:
    compatibility-verifier:
      enabled: false
  main:
    allow-bean-definition-overriding: true

initializr:
  env:
    force-ssl: true
    platform:
      compatibility-range: 7.0.0
  name:
    value: cas
  description:
    value: 'WAR overlay to use as a starting template for Apereo CAS deployments.'
  group-id:
    value: org.apereo.cas
  artifact-id:
    value: cas
  version:
    value: 1.0.0
  package-name:
    value: org.apereo
  javaVersions:
    - id: 21
      default: true
  languages:
    - name: Java
      id: java
      default: true
  packagings:
    - name: War
      id: war
      default: true
  types:
    - name: CAS Overlay Gradle Project Zip
      id: cas-overlay
      description: Generate a Gradle-based project as a zip file
      tags:
        build: cas-overlay
        format: project
      default: true
      action: /starter.zip
    - name: CAS Overlay Gradle Project TGZ
      id: cas-overlay
      description: Generate a Gradle-based project as a tgz file
      tags:
        build: cas-overlay
        format: project
      default: false
      action: /starter.tgz
    - name: CAS Config Server Overlay Gradle Project Zip
      id: cas-config-server-overlay
      description: Generate a Gradle-based project as a zip file
      tags:
        build: cas-config-server-overlay
        format: project
      default: true
      action: /starter.zip
    - name: CAS Config Server Overlay Gradle Project TGZ
      id: cas-config-server-overlay
      description: Generate a Gradle-based project as a tgz file
      tags:
        build: cas-config-server-overlay
        format: project
      default: false
      action: /starter.tgz
